version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: hr-postgres
    environment:
      POSTGRES_USER: moj_user
      POSTGRES_PASSWORD: mojeHaslo
      POSTGRES_DB: hr_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    restart: always

volumes:
  postgres_data:
